language: python
python:
  - 2.6
  - 2.7
install:
  - cp intranet/settings/local.py.example intranet/settings/local.py
  - make exec COMMAND="django-admin.py syncdb --all --noinput"
  - make exec COMMAND="django-admin.py migrate --fake --noinput"
script: make test

notifications:
  irc:
    - "chat.freenode.net#kiberpipa"
  email:
    - domen@dev.si
